@startuml

package Expression {

  interface Expression {
    +evaluate(): Number
  }

  interface Operation {
      -Operator operator (1..1)
      -Expression operands (1..n)
      --
      +evaluate(): Number
    }

  class Number {
    -BigDecimal value (1..1)
    --
    +evaluate(): Number
  }

  enum Operator {
    PLUS,
    MINUS,
    MULTIPLIED_BY,
    DIVIDED_BY
  }

  Operation o-down- Expression
  Operation *-down- Operator
  Number -up-|> Expression
  Operation -up-|> Expression
}

package Compiler {

  class Compiler {
    -Lexer lexer(1..1)
    -ShuntingYardTokenStreamNormaliser normaliser(1..1)
    -Parser parser(1..1)
    --
    +compile(text: String): Expression
  }

  class ShuntingYardTokenStreamNormaliser {
    +normalise(tokens: List<Token>): List<Token>
  }

  class Parser {
    +parse(tokens: List<Token>): Expression
  }

  class Lexer {
    +lex(text: String): List<Token>
  }

  class Token {
    -TokenType type (1..1)
    -String value (1..1)
  }

  class TokenType {
    IDENTIFIER,
    L_PAREN,
    R_PAREN,
    NUMBER,
    OPERATOR
  }

  Compiler *-down- Lexer
  Compiler *-down- Parser
  Compiler *-down- ShuntingYardTokenStreamNormaliser
  Parser -right-> Expression
  Lexer -down-> Token
  Token *-down- TokenType
  Expression -left-> Number
}


@enduml